# A toy on the complementarity of WP+SMT (automatic) and Coq (interactive).
#
#   make        run the demonstration (verify.sh)
#   make clean  remove Coq build artefacts

.PHONY: all verify clean

all: verify

verify:
	@sh verify.sh

clean:
	rm -f *.vo *.vok *.vos *.glob .*.aux .lia.cache .nia.cache *~
